### ISSUE TITLE
Start fails due to relative path

### ISSUE THREAD

**Issue by atcruice** [neo4jrb/neo4j-rake_tasks#44]
I've encountered a minor hurdle with a brand new project. Trying to start an installed Neo4j server with the `rails neo4j:start` command fails. Failure output (I've redacted portions of the path with `…`):
```
$ rails neo4j:start
Starting Neo4j in development...
Active database: graph.db
Directories in use:
  home:         /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development
  config:       /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/conf
  logs:         /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/logs
  plugins:      /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/plugins
  import:       NOT SET
  data:         /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/data
  certificates: /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/certificates
  run:          /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/run
Starting Neo4j.
db/neo4j/development/bin/neo4j: line 418: /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/run/neo4j.pid: No such file or directory
db/neo4j/development/bin/neo4j: line 417: /Users/…/asdf/db/neo4j/development
/Users/…/asdf/db/neo4j/development/logs/neo4j.log: No such file or directory
rails aborted!
Unable to run: db/neo4j/development/bin/neo4j start
/Users/…/.gem/ruby/2.5.1/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:249:in `system_or_fail'
/Users/…/.gem/ruby/2.5.1/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:32:in `start'
/Users/…/.gem/ruby/2.5.1/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/neo4j_server.rake:59:in `block (2 levels) in <main>'
/Users/…/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/…/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/…/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/Users/…/.gem/ruby/2.5.1/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/Users/…/.gem/ruby/2.5.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/…/.gem/ruby/2.5.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/…/.gem/ruby/2.5.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/…/.gem/ruby/2.5.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/…/.gem/ruby/2.5.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/…/.gem/ruby/2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/Users/…/.gem/ruby/2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/…/.gem/ruby/2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => neo4j:start
(See full trace by running task with --trace)
```
**Note the duplication of the file paths separated by a newline.**
If I run the same start command `db/neo4j/development/bin/neo4j start` manually I get the same failure. However, **if I run the same start command prefixed to adjust for the relative path**, everything works:
```
$ ./db/neo4j/development/bin/neo4j start
Active database: graph.db
Directories in use:
  home:         /Users/…/asdf/db/neo4j/development
  config:       /Users/…/asdf/db/neo4j/development/conf
  logs:         /Users/…/asdf/db/neo4j/development/logs
  plugins:      /Users/…/asdf/db/neo4j/development/plugins
  import:       /Users/…/asdf/db/neo4j/development/import
  data:         /Users/…/asdf/db/neo4j/development/data
  certificates: /Users/…/asdf/db/neo4j/development/certificates
  run:          /Users/…/asdf/db/neo4j/development/run
Starting Neo4j.
Started neo4j (pid 83941). It is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /Users/…/asdf/db/neo4j/development/logs/neo4j.log for current status.
```

### Runtime information:

- macOS 10.13.5
- Ruby MRI 2.5.1
- Bundler 1.15.2
- Rails 5.2.0

Project creation:
1. `rails new asdf --template=http://neo4jrb.io/neo4j/neo4j.rb --skip-active-record`
1. `echo 'gem "neo4j-rake_tasks"' >> Gemfile`
1. `bundle`
1. `rails neo4j:install[community-stable,development]`

Neo4j database version: Community 3.4.1
`neo4j` gem version: 9.2.4
`neo4j-core` gem version: 8.1.4
`neo4j-rake_tasks` gem version: 0.7.19

**Comment by alexcruice** [comment]
Has anyone else encountered this?
Should the path used to initialise a `ServerManager` always be absolute? If you can point me in the direction you'd like this addressed, I'm more than happy to submit a pull request.
