### ISSUE TITLE
Error when executing rake neo4j:schema:load

### ISSUE THREAD

**Issue by ghost** [neo4jrb/neo4j-rake_tasks#52]
```
 ActiveGraph::Migrations::SchemaMigration 
  MATCH (n:`ActiveGraph::Migrations::SchemaMigration`)
  RETURN n 
 CYPHER 
  WITH $versions AS versions
  UNWIND versions AS version
  MERGE (:`ActiveGraph::Migrations::SchemaMigration` {migration_id: version}) | {:versions=>["20171123022930", "20171202201946", "20180621001731", "20180621001753", "20180621001756", "20180625124155", "20180625124211", "20180625124231", "20180702224058", "20180720044745", "20180726195825", "20190114185735", "20190114185752", "20190310051342", "20190310051349", "20190312181638", "20190323172351", "20191017075146", "20191128115729", "20200509173511", "20200809204251", "20200809204301", "20201126223952", "20201223200025", "20201223200049", "20201223200136"]}
rake aborted!
Neo4j::Driver::Exceptions::ClientException: Tried to execute Write query after executing Schema modification
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/jruby/neo4j/driver/ext/exception_mapper.rb:19:in `reraise'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/jruby/neo4j/driver/ext/exception_checkable.rb:10:in `check'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/jruby/neo4j/driver/ext/internal_session.rb:19:in `block in write_transaction'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:43:in `run_transaction_work'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:37:in `block in send_transaction'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/lib/neo4j/driver/auto_closable.rb:19:in `block in session'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:36:in `send_transaction'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:22:in `write_transaction'
/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/tasks/migration.rake:92:in `block in <main>'

Caused by:
Java::OrgNeo4jDriverExceptions::ClientException: Tried to execute Write query after executing Schema modification
org.neo4j.driver.internal.util.Futures.blockingGet(org/neo4j/driver/internal/util/Futures.java:143)
org.neo4j.driver.internal.InternalTransaction.commit(org/neo4j/driver/internal/InternalTransaction.java:39)
org.neo4j.driver.internal.InternalSession.lambda$transaction$4(org/neo4j/driver/internal/InternalSession.java:154)
org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(org/neo4j/driver/internal/retry/ExponentialBackoffRetryLogic.java:103)
org.neo4j.driver.internal.InternalSession.transaction(org/neo4j/driver/internal/InternalSession.java:146)
org.neo4j.driver.internal.InternalSession.writeTransaction(org/neo4j/driver/internal/InternalSession.java:124)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)
org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:293)
RUBY.write_transaction(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/jruby/neo4j/driver/ext/internal_session.rb:20)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.neo4j_minus_java_minus_driver_minus_4_dot_2_dot_0_minus_java.jruby.neo4j.driver.ext.exception_checkable.check(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/jruby/neo4j/driver/ext/exception_checkable.rb:8)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.neo4j_minus_java_minus_driver_minus_4_dot_2_dot_0_minus_java.jruby.neo4j.driver.ext.exception_checkable.RUBY$method$check$0$__VARARGS__(home/opencoderx/$_dot_rvm/gems/jruby_minus_9_dot_2_dot_17_dot_0/gems/neo4j_minus_java_minus_driver_minus_4_dot_2_dot_0_minus_java/jruby/neo4j/driver/ext//home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/jruby/neo4j/driver/ext/exception_checkable.rb)
RUBY.write_transaction(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/jruby/neo4j/driver/ext/internal_session.rb:19)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:339)
org.jruby.RubyClass.finvokeWithRefinements(org/jruby/RubyClass.java:514)
org.jruby.RubyBasicObject.send(org/jruby/RubyBasicObject.java:1755)
org.jruby.RubyKernel.send(org/jruby/RubyKernel.java:2200)
org.jruby.RubyKernel$INVOKER$s$send.call(org/jruby/RubyKernel$INVOKER$s$send.gen)
RUBY.run_transaction_work(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:43)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java.lib.active_graph.transactions.invokeOther0:run_transaction_work(home/opencoderx/$_dot_rvm/gems/jruby_minus_9_dot_2_dot_17_dot_0/gems/activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java/lib/active_graph//home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:37)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java.lib.active_graph.transactions.send_transaction(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:37)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:291)
org.jruby.RubyProc$INVOKER$i$call.call(org/jruby/RubyProc$INVOKER$i$call.gen)
RUBY.session(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/neo4j-java-driver-4.2.0-java/lib/neo4j/driver/auto_closable.rb:19)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:339)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java.lib.active_graph.transactions.invokeOther9:session(home/opencoderx/$_dot_rvm/gems/jruby_minus_9_dot_2_dot_17_dot_0/gems/activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java/lib/active_graph//home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:36)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java.lib.active_graph.transactions.send_transaction(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:36)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java.lib.active_graph.transactions.invokeOther0:send_transaction(home/opencoderx/$_dot_rvm/gems/jruby_minus_9_dot_2_dot_17_dot_0/gems/activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java/lib/active_graph//home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:22)
home.opencoderx.$_dot_rvm.gems.jruby_minus_9_dot_2_dot_17_dot_0.gems.activegraph_minus_11_dot_0_dot_0_dot_beta_dot_4_minus_java.lib.active_graph.transactions.write_transaction(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/transactions.rb:22)
RUBY.<main>(/home/opencoderx/.rvm/gems/jruby-9.2.17.0/gems/activegraph-11.0.0.beta.4-java/lib/active_graph/tasks/migration.rake:92)
org.jruby.RubyProc.call(org/jruby/RubyProc.java:299)
org.jruby.RubyProc$INVOKER$i$call.call(org/jruby/RubyProc$INVOKER$i$call.gen)
RUBY.execute(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:281)
org.jruby.RubyArray.each(org/jruby/RubyArray.java:1809)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)
RUBY.execute(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:281)
RUBY.invoke_with_call_chain(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:219)
RUBY.mon_synchronize(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/stdlib/monitor.rb:237)
org.jruby.RubyThread.handle_interrupt(org/jruby/RubyThread.java:759)
org.jruby.RubyThread$INVOKER$s$1$0$handle_interrupt.call(org/jruby/RubyThread$INVOKER$s$1$0$handle_interrupt.gen)
RUBY.mon_synchronize(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/stdlib/monitor.rb:236)
org.jruby.RubyThread.handle_interrupt(org/jruby/RubyThread.java:759)
org.jruby.RubyThread$INVOKER$s$1$0$handle_interrupt.call(org/jruby/RubyThread$INVOKER$s$1$0$handle_interrupt.gen)
RUBY.mon_synchronize(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/stdlib/monitor.rb:233)
RUBY.invoke_with_call_chain(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:199)
RUBY.invoke(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/task.rb:188)
RUBY.invoke_task(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:160)
RUBY.top_level(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:116)
org.jruby.RubyArray.each(org/jruby/RubyArray.java:1809)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)
RUBY.top_level(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:116)
RUBY.run_with_threads(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:125)
RUBY.top_level(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:110)
RUBY.run(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:83)
RUBY.standard_exception_handling(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:186)
RUBY.run(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/lib/rake/application.rb:80)
RUBY.<main>(/home/opencoderx/.rvm/rubies/jruby-9.2.17.0/lib/ruby/gems/shared/gems/rake-13.0.3/exe/rake:27)
org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1218)
org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2785)
org.jruby.RubyKernel.loadCommon(org/jruby/RubyKernel.java:1039)
org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1009)
org.jruby.RubyKernel$INVOKER$s$load.call(org/jruby/RubyKernel$INVOKER$s$load.gen)
java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
org.jruby.Ruby.runScript(org/jruby/Ruby.java:1205)
org.jruby.Ruby.runNormally(org/jruby/Ruby.java:1128)
org.jruby.Ruby.runNormally(org/jruby/Ruby.java:1146)
org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:958)
org.jruby.Main.doRunFromMain(org/jruby/Main.java:400)
org.jruby.Main.internalRun(org/jruby/Main.java:292)
org.jruby.Main.run(org/jruby/Main.java:234)
org.jruby.Main.main(org/jruby/Main.java:206)
Tasks: TOP => neo4j:schema:load

```

Additional information which could be helpful if relevent to your issue:

### Runtime information:

Neo4j database version: 4.2
`neo4j` gem version:  gem 'activegraph', '~> 11.0.0.beta.4'
`neo4j-core` gem version:  gem 'neo4j-java-driver', '4.2.0'

**Comment by mythilikarra** [comment]
I have the same issue, how did you fix this?
