### ISSUE TITLE
neo4j installation fails: Errno::ENOENT: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by maasha** [neo4jrb/neo4j-rake_tasks#55]
I am trying to install and run neo4j from Ruby without Rails, but the installation fails: help appreciated!

Gemfile:

```
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'neo4j', '~> 9.6.2'
gem 'neo4j-rake_tasks', '~> 0.7.19'

group :development do
  gem 'ruby-prof', '~> 1.4.3'
end

```

And in terminal after `bundle install`:

```
$ rake neo4j:install[community-latest,development]
Install Neo4j (development environment)...
Retrieving latest version...
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - https://raw.githubusercontent.com/neo4jrb/neo4j-rake_tasks/master/neo4j_versions.yml
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:293:in `initialize'
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:293:in `open'
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:293:in `neo4j_versions'
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:257:in `block in version_from_edition'
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:253:in `gsub'
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:253:in `version_from_edition'
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/server_manager.rb:16:in `install'
/usr/local/lib/ruby/gems/3.1.0/gems/neo4j-rake_tasks-0.7.19/lib/neo4j/rake_tasks/neo4j_server.rake:39:in `block (2 levels) in <top (required)>'
Tasks: TOP => neo4j:install
(See full trace by running task with --trace)
```

And checking with the browser, https://raw.githubusercontent.com/neo4jrb/neo4j-rake_tasks/master/neo4j_versions.yml looks just fine: 

```
---
  stable: &stable '3.4.1'
  alpha: 3.5.0-alpha04
  milestone: 3.4.1
  rc: &rc 3.4.0-rc02

  # aliases
  latest: *stable
  release-candidate: *rc
```

**Comment by hraynaud** [comment]
having same issue on M1 Mac

**Comment by nomasprime** [comment]
Confirmed, doesn't work. And, looking at this issue, unmaintained.

**Comment by benngarcia** [comment]
Opened a PR a while ago. You can fork and run or just modify yourself. It's a single line change https://github.com/neo4jrb/neo4j-rake_tasks/pull/54
